### ISSUE TITLE
Port range request

### ISSUE THREAD

**Issue by boerio** [fireeye/flare-fakenet-ng#1]
The ability to define a range of ports could be extremely useful, especially when investigating things that are truly unknown or operating a sinkhole.  I envision two ideas in the config file, one that accepts a comma-separated list of values and another that specifies starting and ending port values.  Examples follow.

```
[HTTP Common Ports]
Enabled:               True
Port:                  80,81,88,8080,8081,8088
Protocol:              TCP
Listener:              HTTPListener
UseSSL:                Yes
Webroot:               defaultFiles/
DumpHTTPPosts:         Yes
DumpHTTPPostFilePrefix:            http

[Custom VNC listener]
Enabled:               True
Port:                  5901-5999
Protocol:              TCP
Listener:              customVnc
UseSSL:                No
```

**Comment by iphelix** [comment]
Implemented.
