### ISSUE TITLE
pydivert 2.x does not contain enum.py, causing fakenet.py to have errors

### ISSUE THREAD

**Issue by lor16geylang** [fireeye/flare-fakenet-ng#11]
Installing flare will get the latest pydivert (currently 2.0.4), which does not contain enum.py.

To be able to run it successfully, the following release must be manually installed:
https://github.com/ffalcinelli/pydivert/releases/tag/1.0.2

**Comment by iphelix** [comment]
Implemented support for PyDivert 2.0.x.
