### ISSUE TITLE
Cannot run binary package on Win XP

### ISSUE THREAD

**Issue by TheOnlyRealTodd** [fireeye/flare-fakenet-ng#12]
Does this software support Windows XP in 32 bit?

**Comment by mr-tz** [comment]
From  [README.md](https://github.com/fireeye/flare-fakenet-ng/blob/master/README.md): "Only Windows Vista+ is supported. Please use the original Fakenet for Windows XP/2003 operating systems."
You can find the original Fakenet at https://practicalmalwareanalysis.com/fakenet/.
