### ISSUE TITLE
FakeNet-NG to Python 3

### ISSUE THREAD

**Issue by strictlymike** [fireeye/flare-fakenet-ng#153]
Migrate FakeNet-NG to Python 3. Scope includes:
* The `setup.py` installation script
* The FakeNet-NG script entry point, `fakenet.py`
* Update WinDivert libraries/drivers in support of Pydivert (`windivert` directory) if necessary
* Custom Provider Example (`CustomProviderExample.py` under `configs`)
* Linux and Windows Diverters and associated code
* All listeners

Use the full test procedure for both Windows and Linux testing, to confirm that the results using Python 3 match the results using Python 2.

Before releasing, verify that the setup requirements for the Python 3 version of FakeNet-NG are well-understood and are taken care of in `setup.py` file (and/or documented in `README.md`).

**Comment by DrJZoidberg** [comment]
@tinajn what's the status of this? I can lend a hand in my free time if you want

**Comment by tinajn** [comment]
@DrJZoidberg Development is completed, testing the code right now.

**Comment by samrath-sudesh-acharya** [comment]
@tinajn @DrJZoidberg since the codebase is changed to python3, shall I wait for the codebase to get updated or could I contribute in python2?

**Comment by tinajn** [comment]
@samrath-sudesh-acharya I recommend waiting until we merge the porting code (expect an update next week).

**Comment by samrath-sudesh-acharya** [comment]
@tinajn ok
