### ISSUE TITLE
Syslog?

### ISSUE THREAD

**Issue by boerio** [fireeye/flare-fakenet-ng#3]
If you're operating fakenet as a sinkhole, the ability to write to syslog, so it could be sent to a SIEM would be a great capability.

**Comment by strictlymike** [comment]
FakeNet-NG uses the Python `logging` module, so perhaps the `SysLogHandler` under `logging.handlers` could make short work of this? If it isn't a no-code solution, then it still seems like it should be pretty quick to integrate that.

https://docs.python.org/2/library/logging.handlers.html

**Comment by vavarachen** [comment]
Boerio,

See pull request https://github.com/fireeye/flare-fakenet-ng/pull/69. It should address your local and remote syslog needs.

**Comment by strictlymike** [comment]
Closed via #91 with `-s` argument in version 1.4.1.
