### ISSUE TITLE
Failed to open /proc/net/netfilter/nfnetlink_queue error message not sufficiently explanatory

### ISSUE THREAD

**Issue by strictlymike** [fireeye/flare-fakenet-ng#34]
The following message could do a better job of indicating that the user needn't worry.

```
[          Diverter] Failed to open /proc/net/netfilter/nfnetlink_queue to enumerate netfilter netlink queues, caller may procee
d as if none are in use: 
```

**Comment by liqingjia** [comment]
I find a solution,you can try.
The service file dns-clean.service from the /lib/systemd/system
open it,
replace ExecStartPre=/bin/mkdir /var/run/pppconfig
with ExecStartPre=/bin/mkdir -p /var/run/pppconfig
good luck.
