### ISSUE TITLE
Suggested documentation correction

### ISSUE THREAD

**Issue by the-IMOL** [fireeye/flare-fakenet-ng#5]
Under the Readme.md section where it states:

> **Stand-alone executable**
> It is easiest to simply download the compiled version which can be obtained from the releases page:
> _https://www.github.com/fireeye/flare-fakenet-ng/releases_

Suggested correction is to remove "www" from the URL because the link occasionally does not redirect to "github.com" and creates a 404 error. Change link to: 
 _https://github.com/fireeye/flare-fakenet-ng/releases_

**Comment by iphelix** [comment]
Fixed in the latest version of documentation.
