### ISSUE TITLE
HTTPListener and FTPListener are never used 

### ISSUE THREAD

**Issue by garsim** [fireeye/flare-fakenet-ng#53]
I'm trying to handle some basic requests to download files or to list a ftp address but in both cases FakeNet replies always with the DNSServer. Why? I've tried also to force all traffic to HTTPListener or FTPListener but nothing happens (FakeNet doesn't replies to the requests).

Any advise?

**Comment by strictlymike** [comment]
Based on our email conversation, it sounds like this was a VM configuration issue (you built a new VM and then the same FakeNet-NG code worked correctly).

I am noting (in case this recurs) that you were using the latest FakeNet-NG as of 10/25 (default listener = proxy listener) on Windows with your default gateway set to x.x.x.254. Please let me know if you have any further trouble.
