### ISSUE TITLE
sending raw files in HTTP

### ISSUE THREAD

**Issue by cecio** [fireeye/flare-fakenet-ng#61]
Hi.
I started to implement in the code the possibility to optionally send RAW html files, I mean something like

```
HTTP/1.1 302 Found
Cache-Control: private
Content-Type: text/html; charset=UTF-8
Referrer-Policy: no-referrer
Location: http://www.google.it/?gfe_rd=cr&dcr=0&ei=-hMOWpvLOuzBXtDhiegJ
Content-Length: 266
Date: Thu, 16 Nov 2017 22:40:58 GMT

<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>

```
In this way you can have more control on the replies and sending specific codes or formats.
For the time being I started to do it in a very naive way:

for example if I do a GET /myfile

I search in the "defaultFiles" for a file named "myfile.RAW". If it exists, it send it without additional headers or config (assuming that they are in the file).
Do you have any suggestion on a better approach on this? Then, as soon as I'll have this cleaned up, I'll share it if you are interested.

Thanks,

**Comment by cecio** [comment]
I worked a bit on this. I did the following in httplistener.py

- when processing GET/POST <filename> the process looks also for a <filename>.RAW file
- if it does not exists, it works as usual
- if exists, it sends back it
For example, with the following, named "success.txt.RAW"

```
HTTP/1.1 200 OK
Content-Type: text/plain
Content-Length: 8
Last-Modified: Mon, 15 May 2017 18:04:40 GMT
ETag: "ae780585f49b94ce1444eb7d28906123"
Accept-Ranges: bytes
Server: AmazonS3
X-Amz-Cf-Id: DOMFBGDxBc9xK7seJjwbgRcfGUMjatIzbXRAY4nKJan2KJgKx6nM9g==
Cache-Control: no-cache, no-store, must-revalidate
Date: <RAW-DATE>
Connection: close

success

```
I can emulate the Firefox connection portal.
As you can see I also implemented some "variables" replaced at runtime. In this case ("\<RAW-DATE\>") is the current time. May be I can add more.

**Comment by strictlymike** [comment]
Thank you for your suggestion! A FLARE analyst has a similar request involving not URIs but instead HTTP `Host` headers. I think what we'll do is implement a feature that uses optional extended configuration specific to the `HTTPListener` to direct it to behave differently in certain scenarios. Watch this space for updates ;-)

**Comment by evil-e** [comment]
Here is what I've hacked together for a related use case. Please read the CustomResponse.MD file from this commit: https://github.com/evil-e/flare-fakenet-ng/commit/ea54fa6aee55b7cd1d5dd7cd50ccb1e671bfc163

**Comment by cecio** [comment]
sounds great! thanks!

**Comment by strictlymike** [comment]
Merged <https://github.com/fireeye/flare-fakenet-ng/pull/120> resulting in FakeNet-NG version 1.4.9 which supports this feature. See `docs/CustomResponse.md` for details.
