### ISSUE TITLE
Configuration to let malware retrieve a HTTP response

### ISSUE THREAD

**Issue by ChrisPooh** [fireeye/flare-fakenet-ng#7]
Is there any configuration in Fakenet-NG that is similar to INetSim 's Fake Mode?
Description:
Delivers configured fake files based on the file extension in the HTTP request (e.g. .html or .exe) or static paths

**Comment by mr-tz** [comment]
Fakenet-NG already supports this for the following file types based on mime type: text/html, image/png, image/ico, image/jpeg, application/octet-stream, application/x-msdownload, application/pdf, application/xml (
see https://github.com/fireeye/flare-fakenet-ng/blob/master/fakenet/listeners/HTTPListener.py#L18). Does this feature not work for you?
