### ISSUE TITLE
Fakenet-ng not running on Windows 7 x64 SP1

### ISSUE THREAD

**Issue by jwilczek** [fireeye/flare-fakenet-ng#9]
If I run fakenet32.exe, I get the following error (note 64-bit python is installed):

> 11/23/16 02:01:39 PM [           FakeNet] Error: Please install 64-bit Python interpreter to support diverter functions.

If I run fakenet64.exe, I get the error:
![image](https://cloud.githubusercontent.com/assets/8474603/20576926/92851946-b185-11e6-8579-fd97f17b6810.png)

I've been unable to resolve either of these issues.

Thanks!

**Comment by sdsponger** [comment]
Same thing happens to me running on a 64-bit Win7 SP1 vm under Virtual Box.  Can't seem to figure out how to resolve either...

**Comment by woanware** [comment]
The reason you are having the issue is that you don't have the correct Microsoft run time installed e.g. Microsoft.VC90.CRT (VC++ 2008).

Download it from here: http://www.microsoft.com/download/en/details.aspx?id=26368

Choose the OS architecture specific version you require, download and install.

**Comment by iphelix** [comment]
Closing issue since it appears to be resolved. Please reopen if it reoccurs.
